export const QUESTIONS = [ 
    ["Atatürk Hangi Yılda Doğmuştur?",
    "1987","1881","1861","1956",
    "1881"],
    ["UZUNYAZIUZUNYAZIUZUNYAZIY-UZUNZUNZUNZUZNZUNZUNZUNZUNZUNZUNZU",
    "DENEME1EWRFWEREWRWEREWRFEWFEWFNEWIFUHWEIUFHBEWLIBHRWELIU","DENEME2","DENEME3","DENEME4",
    "DENEME5"]
]